# Generated by Django 4.2.7 on 2023-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsrating',
            name='comment',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='reviewsrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
